CREATE TABLE MESSAGE (
    ID NUMBER PRIMARY KEY,
    TEXT NVARCHAR2(140),
    DATE_SENT DATE,
    DATE_READ DATE,
    USER_FROM NUMBER REFERENCES USERS(ID),
    USER_TO NUMBER REFERENCES USERS(ID),
    DATE_EDITED DATE,
    DATE_DELETED DATE,
    CONSTRAINT DATE_READ_CH CHECK(DATE_SENT <= DATE_READ),
    CONSTRAINT DATE_EDITED_CH CHECK(DATE_EDITED <= DATE_READ),
    CONSTRAINT DATE_DELETED_CH CHECK(DATE_DELETED <= DATE_READ)
);