CREATE TABLE RELATIONSHIP (
    USER_FROM NUMBER REFERENCES USERS(ID),
    USER_TO NUMBER REFERENCES USERS(ID),
    STATUS NVARCHAR2(30),
    CONSTRAINT STATUS_CH CHECK(STATUS IN('FRIENDS', 'REQUEST_SENT', 'DELETED', 'REQUEST_DECLINED', 'PAST_FRIENDS')),
    CONSTRAINT USERS_CH CHECK(USER_FROM != USER_TO),
    CONSTRAINT RELATIONSHIP_PK PRIMARY KEY(USER_FROM, USER_TO)
);

ALTER TABLE RELATIONSHIP DROP CONSTRAINT STATUS_CH;
ALTER TABLE RELATIONSHIP ADD CONSTRAINT STATUS_CH CHECK(STATUS IN('FRIENDS', 'REQUEST_SENT', 'DELETED',
'REQUEST_DECLINED', 'PAST_FRIENDS'));

ALTER TABLE RELATIONSHIP ADD LAST_STATUS_CHANGE DATE;