CREATE TABLE RELATIONSHIP (
    USER_FROM NUMBER REFERENCES USERS(ID),
    USER_TO NUMBER REFERENCES USERS(ID),
    STATUS NVARCHAR2(30),
    CONSTRAINT STATUS_CH CHECK(STATUS IN('FRIENDS', 'REQUEST_SENT', 'NOT_FRIENDS', 'REQUEST_DENIED', 'PAST_FRIENDS')),
    CONSTRAINT USERS_CH CHECK(USER_FROM != USER_TO),
    CONSTRAINT RELATIONSHIP_PK PRIMARY KEY(USER_FROM, USER_TO)
);